const $=id=>document.getElementById(id);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

function buildNetwork(){
  const root=$("neural-net"); root.innerHTML="";
  [5,8,6,4].forEach(count=>{
    const layer=document.createElement("div"); layer.className="layer";
    for(let i=0;i<count;i++){
      const row=document.createElement("div"), node=document.createElement("span"), weight=document.createElement("span");
      node.className="node"; weight.className="weight";
      weight.textContent=(Math.random()*2-1).toFixed(3);
      row.append(node,weight); layer.append(row);
    }
    root.append(layer);
  });
}

async function animateNetwork(){
  const nodes=[...document.querySelectorAll(".node")];
  for(let i=0;i<80;i++){
    nodes.forEach(n=>n.classList.remove("active"));
    for(let j=0;j<Math.max(1,Math.floor(nodes.length/5));j++)
      nodes[Math.floor(Math.random()*nodes.length)].classList.add("active");
    await sleep(35);
  }
  nodes.forEach(n=>n.classList.remove("active"));
}

function renderWave(values){
  const root=$("wave"); root.innerHTML="";
  const max=Math.max(...values.map(Math.abs),1);
  values.forEach(value=>{
    const bar=document.createElement("div"), number=document.createElement("span");
    bar.className="bar"; bar.style.height=Math.max(2,Math.abs(value)/max*150)+"px";
    number.textContent=value; bar.append(number); root.append(bar);
  });
}

function renderGrid(grid){
  const root=$("grid"); root.innerHTML="";
  const flat=grid.flat(), max=Math.max(...flat);
  flat.forEach(value=>{
    const cell=document.createElement("div"); cell.className="cell";
    const v=Math.round(value/Math.max(max,1)*255);
    cell.style.background="rgb("+v+","+v+","+v+")"; cell.textContent=value; root.append(cell);
  });
}

async function generate(){
  $("run").disabled=true; buildNetwork();
  $("text-status").textContent="forward pass";
  $("audio-status").textContent="generating waveform";
  $("image-status").textContent="generating pixels";
  const animation=animateNetwork();
  try{
    const response=await fetch("/api/generate/all",{
      method:"POST",headers:{"Content-Type":"application/json"},
      body:JSON.stringify({prompt:$("prompt").value,seed:Date.now()%100000})
    });
    const result=await response.json();
    await animation;
    $("text-output").textContent=result.text.text;
    $("text-status").textContent=result.text.tokens.length+" tokens · "+result.text.device;
    $("audio").src=result.audio.wav; renderWave(result.audio.amplitudes);
    $("audio-status").textContent=result.audio.duration_seconds+"s · "+result.audio.sample_rate+"Hz";
    $("image").src=result.image.png; renderGrid(result.image.grid);
    $("image-status").textContent="32 × 32 · generated by neural decoder";
  }catch(error){
    $("text-output").textContent=String(error); $("text-status").textContent="error";
  }finally{$("run").disabled=false}
}
$("run").addEventListener("click",generate); buildNetwork();
